"""Prueba de Base de datos

Revision ID: 5aa678157711
Revises: 
Create Date: 2025-03-30 20:53:07.320227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aa678157711'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bastones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('bastones_usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('baston_id', sa.Integer(), nullable=False),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['baston_id'], ['bastones.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contactos_emergencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ubicaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('baston_id', sa.Integer(), nullable=True),
    sa.Column('latitud', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('longitud', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['baston_id'], ['bastones.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alertas_emergencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo_alerta', sa.Enum('caída', 'zona de riesgo', name='tipo_alerta'), nullable=False),
    sa.Column('ubicacion_id', sa.Integer(), nullable=True),
    sa.Column('contacto_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'atendida', name='estado_alerta'), nullable=False),
    sa.Column('fecha_alerta', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contacto_id'], ['contactos_emergencia.id'], ),
    sa.ForeignKeyConstraint(['ubicacion_id'], ['ubicaciones.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alertas_emergencia')
    op.drop_table('ubicaciones')
    op.drop_table('contactos_emergencia')
    op.drop_table('bastones_usuarios')
    op.drop_table('usuarios')
    op.drop_table('roles')
    op.drop_table('bastones')
    # ### end Alembic commands ###
